title: The Blogzzolo
author: Rodrigo Bozzolo
email: contact@bozz.cl
tagline: Rodrigo Bozzolo
description: >
  Personal blog of Rodrigo Bozzolo. I write about tech, random musings and whatever I find fun.
  Blog personal de Rodrigo Bozzolo. Escribo sobre tecnologia, temas varios y lo que sea que me dé la gana.
baseurl: ""
url: "https://www.bozz.cl"
show_excerpts: true
excerpt_separator: <!--more-->

theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-responsive-image

languages: ["en", "es_CL"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false

minima:
  skin: dark
  social_links:
    github:  thebozzcl
    linkedin: rodrigo-bozzolo

sass:
  sourcemap: never

fastcomments:
  tenantId: "IeX0qIpHi"

# Copied and customized from https://itsgus.dev/2020/jekyll-responsive-images - thanks Gus!
responsive_image:
  template: _includes/dynamic-image.html
#  base_path: images/
#  output_path_format: images/resized/%{dirname}/%{filename}-%{width}.%{extension}
  base_path: images # update this to match the path to your image folder (default: assets)
  output_path_format: images/srcset/%{width}/%{basename} # the destination path for the resized images; configure to suit your project structur
  sizes:
    - width: 480
      quality: 80
    - width: 800
    - width: 1400
      quality: 90

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - _build.sh
